{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from datetime import datetime"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Создание бд (не работает сука)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-- MySQL Script generated by MySQL Workbench\n",
      "-- Tue Dec 10 18:52:12 2019\n",
      "-- Model: New Model    Version: 1.0\n",
      "-- MySQL Workbench Forward Engineering\n",
      "\n",
      "SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;\n",
      "SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;\n",
      "SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';\n",
      "\n",
      "-- -----------------------------------------------------\n",
      "-- Schema logic\n",
      "-- -----------------------------------------------------\n",
      "DROP SCHEMA IF EXISTS `logic` ;\n",
      "\n",
      "-- -----------------------------------------------------\n",
      "-- Schema logic\n",
      "-- -----------------------------------------------------\n",
      "CREATE SCHEMA IF NOT EXISTS `logic` DEFAULT CHARACTER SET utf8 ;\n",
      "USE `logic` ;\n",
      "\n",
      "-- -----------------------------------------------------\n",
      "-- Table `logic`.`User`\n",
      "-- -----------------------------------------------------\n",
      "CREATE TABLE IF NOT EXISTS `logic`.`User` (\n",
      "  `UserID` INT(11) NOT NULL,\n",
      "  `FullName` TEXT NOT NULL,\n",
      "  `e-mail` TEXT NOT NULL,\n",
      "  `UserStatus` TINYINT(1) NOT NULL,\n",
      "  PRIMARY KEY (`UserID`))\n",
      "ENGINE = InnoDB;\n",
      "\n",
      "\n",
      "-- -----------------------------------------------------\n",
      "-- Table `logic`.`Student`\n",
      "-- -----------------------------------------------------\n",
      "CREATE TABLE IF NOT EXISTS `logic`.`Student` (\n",
      "  `StudentID` VARCHAR(45) NOT NULL,\n",
      "  `GroupID` INT(11) NULL,\n",
      "  `UserID` INT(11) NOT NULL,\n",
      "  INDEX `fk_Students_Users_idx` (`UserID` ASC) VISIBLE,\n",
      "  PRIMARY KEY (`StudentID`, `UserID`),\n",
      "  CONSTRAINT `fk_Students_Users`\n",
      "    FOREIGN KEY (`UserID`)\n",
      "    REFERENCES `logic`.`User` (`UserID`)\n",
      "    ON DELETE NO ACTION\n",
      "    ON UPDATE NO ACTION)\n",
      "ENGINE = InnoDB;\n",
      "\n",
      "\n",
      "-- -----------------------------------------------------\n",
      "-- Table `logic`.`Group`\n",
      "-- -----------------------------------------------------\n",
      "CREATE TABLE IF NOT EXISTS `logic`.`Group` (\n",
      "  `GroupID` INT(11) NOT NULL,\n",
      "  `GroupName` TEXT NULL,\n",
      "  `CreatorID` INT(11) NULL,\n",
      "  PRIMARY KEY (`GroupID`),\n",
      "  INDEX `fk_Group_User1_idx` (`CreatorID` ASC) VISIBLE,\n",
      "  CONSTRAINT `fk_Group_User1`\n",
      "    FOREIGN KEY (`CreatorID`)\n",
      "    REFERENCES `logic`.`User` (`UserID`)\n",
      "    ON DELETE NO ACTION\n",
      "    ON UPDATE NO ACTION)\n",
      "ENGINE = InnoDB;\n",
      "\n",
      "\n",
      "-- -----------------------------------------------------\n",
      "-- Table `logic`.`Assignment`\n",
      "-- -----------------------------------------------------\n",
      "CREATE TABLE IF NOT EXISTS `logic`.`Assignment` (\n",
      "  `AssignmentID` INT(11) NOT NULL,\n",
      "  `Description` LONGTEXT NULL,\n",
      "  `GroupID` INT(11) NOT NULL,\n",
      "  `DueDate` DATETIME NULL,\n",
      "  PRIMARY KEY (`AssignmentID`),\n",
      "  INDEX `fk_Assigmnet_Group1_idx` (`GroupID` ASC) VISIBLE,\n",
      "  CONSTRAINT `fk_Assigmnet_Group1`\n",
      "    FOREIGN KEY (`GroupID`)\n",
      "    REFERENCES `logic`.`Group` (`GroupID`)\n",
      "    ON DELETE NO ACTION\n",
      "    ON UPDATE NO ACTION)\n",
      "ENGINE = InnoDB;\n",
      "\n",
      "\n",
      "-- -----------------------------------------------------\n",
      "-- Table `logic`.`Task`\n",
      "-- -----------------------------------------------------\n",
      "CREATE TABLE IF NOT EXISTS `logic`.`Task` (\n",
      "  `TaskID` INT(11) NOT NULL,\n",
      "  `AssignmentID` INT(11) NOT NULL,\n",
      "  `Description` LONGTEXT NULL,\n",
      "  PRIMARY KEY (`TaskID`),\n",
      "  INDEX `fk_Task_Course1_idx` (`AssignmentID` ASC) VISIBLE,\n",
      "  CONSTRAINT `fk_Task_Course1`\n",
      "    FOREIGN KEY (`AssignmentID`)\n",
      "    REFERENCES `logic`.`Assignment` (`AssignmentID`)\n",
      "    ON DELETE NO ACTION\n",
      "    ON UPDATE NO ACTION)\n",
      "ENGINE = InnoDB;\n",
      "\n",
      "\n",
      "-- -----------------------------------------------------\n",
      "-- Table `logic`.`Students`\n",
      "-- -----------------------------------------------------\n",
      "CREATE TABLE IF NOT EXISTS `logic`.`Students` (\n",
      "  `StudentID` INT(11) NOT NULL AUTO_INCREMENT,\n",
      "  `UserID` INT(11) NOT NULL,\n",
      "  `GroupID` INT(11) NOT NULL,\n",
      "  INDEX `fk_Participants_Group1_idx` (`GroupID` ASC) VISIBLE,\n",
      "  INDEX `fk_Participants_User2_idx` (`UserID` ASC) VISIBLE,\n",
      "  PRIMARY KEY (`UserID`, `GroupID`),\n",
      "  UNIQUE INDEX `StudentID_UNIQUE` (`StudentID` ASC) VISIBLE,\n",
      "  CONSTRAINT `fk_Participants_Group1`\n",
      "    FOREIGN KEY (`GroupID`)\n",
      "    REFERENCES `logic`.`Group` (`GroupID`)\n",
      "    ON DELETE NO ACTION\n",
      "    ON UPDATE NO ACTION,\n",
      "  CONSTRAINT `fk_Participants_User2`\n",
      "    FOREIGN KEY (`UserID`)\n",
      "    REFERENCES `logic`.`User` (`UserID`)\n",
      "    ON DELETE NO ACTION\n",
      "    ON UPDATE NO ACTION)\n",
      "ENGINE = InnoDB;\n",
      "\n",
      "\n",
      "-- -----------------------------------------------------\n",
      "-- Table `logic`.`Submissions`\n",
      "-- -----------------------------------------------------\n",
      "CREATE TABLE IF NOT EXISTS `logic`.`Submissions` (\n",
      "  `SubmissionID` INT(11) NOT NULL AUTO_INCREMENT,\n",
      "  `TaskID` INT(11) NOT NULL,\n",
      "  `StudentID` INT(11) NOT NULL,\n",
      "  `Date` DATETIME NOT NULL,\n",
      "  `Content` LONGTEXT NOT NULL,\n",
      "  INDEX `fk_Solution_Task1_idx` (`TaskID` ASC) VISIBLE,\n",
      "  INDEX `fk_Submissions_Participants1_idx` (`StudentID` ASC) VISIBLE,\n",
      "  PRIMARY KEY (`TaskID`, `StudentID`),\n",
      "  UNIQUE INDEX `SubmissionID_UNIQUE` (`SubmissionID` ASC) VISIBLE,\n",
      "  CONSTRAINT `fk_Solution_Task1`\n",
      "    FOREIGN KEY (`TaskID`)\n",
      "    REFERENCES `logic`.`Task` (`TaskID`)\n",
      "    ON DELETE NO ACTION\n",
      "    ON UPDATE NO ACTION,\n",
      "  CONSTRAINT `fk_Submissions_Participants1`\n",
      "    FOREIGN KEY (`StudentID`)\n",
      "    REFERENCES `logic`.`Students` (`StudentID`)\n",
      "    ON DELETE NO ACTION\n",
      "    ON UPDATE NO ACTION)\n",
      "ENGINE = InnoDB;\n",
      "\n",
      "\n",
      "-- -----------------------------------------------------\n",
      "-- Table `logic`.`Teachers`\n",
      "-- -----------------------------------------------------\n",
      "CREATE TABLE IF NOT EXISTS `logic`.`Teachers` (\n",
      "  `TeacherID` INT(11) NOT NULL AUTO_INCREMENT,\n",
      "  `UserID` INT(11) NOT NULL,\n",
      "  `GroupID` INT(11) NOT NULL,\n",
      "  INDEX `fk_Teachers_Group1_idx` (`GroupID` ASC) VISIBLE,\n",
      "  PRIMARY KEY (`UserID`, `GroupID`),\n",
      "  UNIQUE INDEX `TeacherID_UNIQUE` (`TeacherID` ASC) VISIBLE,\n",
      "  CONSTRAINT `fk_Teachers_User1`\n",
      "    FOREIGN KEY (`UserID`)\n",
      "    REFERENCES `logic`.`User` (`UserID`)\n",
      "    ON DELETE NO ACTION\n",
      "    ON UPDATE NO ACTION,\n",
      "  CONSTRAINT `fk_Teachers_Group1`\n",
      "    FOREIGN KEY (`GroupID`)\n",
      "    REFERENCES `logic`.`Group` (`GroupID`)\n",
      "    ON DELETE NO ACTION\n",
      "    ON UPDATE NO ACTION)\n",
      "ENGINE = InnoDB;\n",
      "\n",
      "\n",
      "-- -----------------------------------------------------\n",
      "-- Table `logic`.`Supervisors`\n",
      "-- -----------------------------------------------------\n",
      "CREATE TABLE IF NOT EXISTS `logic`.`Supervisors` (\n",
      "  `SupervisorID` INT(11) NOT NULL AUTO_INCREMENT,\n",
      "  `TeacherID` INT(11) NOT NULL,\n",
      "  `SubmissionID` INT(11) NOT NULL,\n",
      "  INDEX `fk_Supervisors_Submissions1_idx` (`SubmissionID` ASC) VISIBLE,\n",
      "  UNIQUE INDEX `SupervisorID_UNIQUE` (`SupervisorID` ASC) VISIBLE,\n",
      "  PRIMARY KEY (`TeacherID`, `SubmissionID`),\n",
      "  CONSTRAINT `fk_Supervisors_Teachers1`\n",
      "    FOREIGN KEY (`TeacherID`)\n",
      "    REFERENCES `logic`.`Teachers` (`TeacherID`)\n",
      "    ON DELETE NO ACTION\n",
      "    ON UPDATE NO ACTION,\n",
      "  CONSTRAINT `fk_Supervisors_Submissions1`\n",
      "    FOREIGN KEY (`SubmissionID`)\n",
      "    REFERENCES `logic`.`Submissions` (`SubmissionID`)\n",
      "    ON DELETE NO ACTION\n",
      "    ON UPDATE NO ACTION)\n",
      "ENGINE = InnoDB;\n",
      "\n",
      "\n",
      "-- -----------------------------------------------------\n",
      "-- Table `logic`.`Grades`\n",
      "-- -----------------------------------------------------\n",
      "CREATE TABLE IF NOT EXISTS `logic`.`Grades` (\n",
      "  `GradeID` INT(11) NOT NULL,\n",
      "  `SupervisorID` INT(11) NOT NULL,\n",
      "  `Grade` INT(11) NOT NULL,\n",
      "  `Date` DATETIME NOT NULL,\n",
      "  INDEX `fk_Grades_Supervisors1_idx` (`SupervisorID` ASC) VISIBLE,\n",
      "  PRIMARY KEY (`GradeID`),\n",
      "  CONSTRAINT `fk_Grades_Supervisors1`\n",
      "    FOREIGN KEY (`SupervisorID`)\n",
      "    REFERENCES `logic`.`Supervisors` (`SupervisorID`)\n",
      "    ON DELETE NO ACTION\n",
      "    ON UPDATE NO ACTION)\n",
      "ENGINE = InnoDB;\n",
      "\n",
      "\n",
      "-- -----------------------------------------------------\n",
      "-- Table `logic`.`SupervisorComment`\n",
      "-- -----------------------------------------------------\n",
      "CREATE TABLE IF NOT EXISTS `logic`.`SupervisorComment` (\n",
      "  `CommentID` INT(11) NOT NULL,\n",
      "  `SupervisorID` INT(11) NOT NULL,\n",
      "  `Date` DATETIME NOT NULL,\n",
      "  `Comment` LONGTEXT NOT NULL,\n",
      "  PRIMARY KEY (`CommentID`),\n",
      "  INDEX `fk_SupervisorComment_Supervisors1_idx` (`SupervisorID` ASC) VISIBLE,\n",
      "  CONSTRAINT `fk_SupervisorComment_Supervisors1`\n",
      "    FOREIGN KEY (`SupervisorID`)\n",
      "    REFERENCES `logic`.`Supervisors` (`SupervisorID`)\n",
      "    ON DELETE NO ACTION\n",
      "    ON UPDATE NO ACTION)\n",
      "ENGINE = InnoDB;\n",
      "\n",
      "\n",
      "-- -----------------------------------------------------\n",
      "-- Table `logic`.`StudentComment`\n",
      "-- -----------------------------------------------------\n",
      "CREATE TABLE IF NOT EXISTS `logic`.`StudentComment` (\n",
      "  `CommentID` INT(11) NOT NULL,\n",
      "  `SubmissionID` INT(11) NOT NULL,\n",
      "  `Date` DATETIME NOT NULL,\n",
      "  `Comment` LONGTEXT NULL,\n",
      "  INDEX `fk_StudentComment_Submissions1_idx` (`SubmissionID` ASC) VISIBLE,\n",
      "  PRIMARY KEY (`CommentID`),\n",
      "  CONSTRAINT `fk_StudentComment_Submissions1`\n",
      "    FOREIGN KEY (`SubmissionID`)\n",
      "    REFERENCES `logic`.`Submissions` (`SubmissionID`)\n",
      "    ON DELETE NO ACTION\n",
      "    ON UPDATE NO ACTION)\n",
      "ENGINE = InnoDB;\n",
      "\n",
      "\n",
      "SET SQL_MODE=@OLD_SQL_MODE;\n",
      "SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;\n",
      "SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;\n",
      "\n",
      "Connected to DB: 127.0.0.1\n",
      "Error: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;\\nSET @OLD' at line 7\")\n"
     ]
    },
    {
     "ename": "SystemExit",
     "evalue": "1",
     "output_type": "error",
     "traceback": [
      "An exception has occurred, use %tb to see the full traceback.\n",
      "\u001b[0;31mSystemExit\u001b[0m\u001b[0;31m:\u001b[0m 1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py:2890: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.\n",
      "  warn(\"To exit: use 'exit', 'quit', or Ctrl-D.\", stacklevel=1)\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import pymysql\n",
    "import sys\n",
    "f = open('../create_logic.sql')\n",
    "load_sql = f.read()\n",
    "print(load_sql)\n",
    "host = '127.0.0.1'\n",
    "user = 'user'\n",
    "password = 'guizeppe'\n",
    "try:\n",
    "    con = pymysql.connect(host=host,\n",
    "                            user=user,\n",
    "                            password=password,\n",
    "                            autocommit=True,\n",
    "                            local_infile=1)\n",
    "    print('Connected to DB: {}'.format(host))\n",
    "    # Create cursor and execute Load SQL\n",
    "    cursor = con.cursor()\n",
    "    cursor.execute(load_sql)\n",
    "    print('Succuessfully loaded the table from csv.')\n",
    "    con.close()\n",
    "except Exception as e:\n",
    "    print('Error: {}'.format(str(e)))\n",
    "    sys.exit(1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Загрузка данных"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pymysql\n",
    "import os\n",
    "import sys\n",
    "def csv_to_mysql(file_name, table_name):\n",
    "    '''\n",
    "    This function load a csv file to MySQL table according to\n",
    "    the load_sql statement.\n",
    "    '''\n",
    "    \n",
    "    path = os.path.abspath(os.curdir)\n",
    "    path = os.path.join(path, file_name)\n",
    "    load_sql = \"LOAD DATA LOCAL INFILE '\" + path + \"' INTO TABLE \" + table_name + \" FIELDS TERMINATED BY ',' ENCLOSED BY '\" +'\"'+\"' IGNORE 1 LINES;\"\n",
    "    host = '127.0.0.1'\n",
    "    user = 'user'\n",
    "    password = 'guizeppe'\n",
    "    try:\n",
    "        con = pymysql.connect(host=host,\n",
    "                                user=user,\n",
    "                                password=password,\n",
    "                                autocommit=True,\n",
    "                                local_infile=1)\n",
    "        print('Connected to DB: {}'.format(host))\n",
    "        # Create cursor and execute Load SQL\n",
    "        cursor = con.cursor()\n",
    "        cursor.execute(load_sql)\n",
    "        print('Succuessfully loaded the table from csv.')\n",
    "        con.close()\n",
    "        \n",
    "    except Exception as e:\n",
    "        print('Error: {}'.format(str(e)))\n",
    "        sys.exit(1)\n",
    "\n",
    "\n",
    "#file_name = 'users.csv'\n",
    "#csv_to_mysql('users.csv', 'data_vault.Users')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Loading pure tables"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('users.csv', 'data.Users')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('groups.csv', 'data.Groups')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('students.csv', 'data.Students')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('teachers.csv', 'data.Teachers')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('assignments.csv', 'data.Assignments')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('tasks.csv', 'data.Tasks')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('submissions.csv', 'data.Submissions')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('supervisors.csv', 'data.Supervisors')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '1' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '2' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '3' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '4' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '5' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '6' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '7' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '8' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '9' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '10' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '11' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '12' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '13' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '14' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '15' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '16' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '17' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '18' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '19' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '20' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '21' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '22' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '23' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '24' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '25' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '26' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '27' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '28' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '29' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '30' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '31' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '32' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '33' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '34' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '35' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '36' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '37' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '38' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '39' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '40' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '41' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '42' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '43' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '44' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '45' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '46' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '47' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '48' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '49' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '50' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '51' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '52' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '53' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '54' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '55' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '56' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '57' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '58' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '59' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '60' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '61' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '62' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '63' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1062, \"Duplicate entry '64' for key 'PRIMARY'\")\n",
      "  result = self._query(query)\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('grades.csv', 'data.Grades')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 55\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 56\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 60\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 130\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 131\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 155\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 156\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 166\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 260\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 289\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 290\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 317\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 318\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 328\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 329\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 333\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 369\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 409\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 410\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 434\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 435\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 447\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 448\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 478\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 479\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 547\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 554\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 555\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 583\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 613\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 614\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 645\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 711\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 725\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 900\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 923\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 924\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 960\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 961\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1006\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1016\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1017\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1041\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1048\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1066\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1222\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1254\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1269\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1274\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1275\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1303\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1304\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1452\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1453\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1495\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1538\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1618\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1636\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1716\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1717\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1752\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1846\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1872\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1877\")\n",
      "  result = self._query(query)\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('student_comments.csv', 'data.StudentsComments')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 22\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 23\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 60\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 61\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 84\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 85\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 162\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 163\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 308\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 309\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 312\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 313\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 486\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 528\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 529\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 551\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 636\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 637\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 815\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 816\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 828\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 834\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 839\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 840\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 876\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 884\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 885\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1021\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1042\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1056\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1057\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1139\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1140\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1249\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1250\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1363\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1451\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1517\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1596\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1603\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1604\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1685\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1686\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1740\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1765\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1766\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1773\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1783\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 1835\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 2010\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 2011\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 2053\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 2072\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 2094\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 2098\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 2139\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 2406\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 2429\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 2430\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 2513\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 2533\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 2548\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 2549\")\n",
      "  result = self._query(query)\n",
      "/home/dmitry/.local/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1264, \"Out of range value for column 'Date' at row 2577\")\n",
      "  result = self._query(query)\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('supervisor_comments.csv', 'data.SupervisorsComments')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('users.csv', 'logic.Users')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('groups.csv', 'logic.Groups')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('students.csv', 'logic.Students')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('teachers.csv', 'logic.Teachers')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('assignments.csv', 'logic.Assignment')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('tasks.csv', 'logic.Task')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('submissions.csv', 'logic.Submissions')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('supervisors.csv', 'logic.Supervisors')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to DB: 127.0.0.1\n",
      "Succuessfully loaded the table from csv.\n"
     ]
    }
   ],
   "source": [
    "csv_to_mysql('grades.csv', 'logic.Grades')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
